### ISSUE TITLE
Some deprecated Node bs

### ISSUE THREAD

**Issue by ruthmoog** [ruthmoog/bee#28]
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

https://github.com/ruthmoog/bee/actions/runs/10356230372

**Comment by quii** [comment]
![CleanShot 2024-08-12 at 18 41 10](https://github.com/user-attachments/assets/976070c4-0703-4fcd-bb94-38e674955764)

4th time's a charm
